using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using PalItemgen.Lookup;
using PalItemgen.Model;

namespace PalItemgen.Export
{
    /// <summary>
    /// Writes the Lua files the mod reads at runtime: pm_config.lua (settings,
    /// stations, presets) and the generated data tables (items, recipes,
    /// enums). Output is plain `return { ... }` chunks so UE4SS's Lua 5.4 can
    /// `require` them; no runtime parsing of JSON is needed in the game.
    /// </summary>
    public static class LuaWriter
    {
        private static string Q(string s)
        {
            if (s == null) return "\"\"";
            var sb = new StringBuilder("\"");
            foreach (var c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < 32) sb.Append("\\").Append(((int)c).ToString("000", CultureInfo.InvariantCulture));   // padded: a digit may follow
                        else sb.Append(c);
                        break;
                }
            }
            return sb.Append('"').ToString();
        }

        private static string N(float v) => v.ToString("0.0###", CultureInfo.InvariantCulture);
        private static string B(bool v) => v ? "true" : "false";

        /// <summary>Lua table key: bare identifier when legal, else ["quoted"].</summary>
        private static string F(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);

        private static readonly HashSet<string> LuaKeywords = new HashSet<string>
        {
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in",
            "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
        };

        private static string Key(string k)
        {
            // a Lua keyword as a bare key ("end = {") makes the whole file unloadable
            if (!string.IsNullOrEmpty(k) && !LuaKeywords.Contains(k) && System.Text.RegularExpressions.Regex.IsMatch(k, "^[A-Za-z_][A-Za-z0-9_]*$"))
                return k;
            return "[" + Q(k) + "]";
        }

        private static string KindName(StationKind k) => k switch
        {
            StationKind.Manager => "manager",
            StationKind.ConsoleSign => "console",
            _ => "line",
        };

        public static string Config(ModProject p, GameData data = null)
        {
            var a = p.Automation;
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_config.lua : PalProductionManager settings.");
            sb.AppendLine("-- GENERATED by PalItemgen on " + DateTime.Now.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) + ".");
            sb.AppendLine("-- Edit by hand if you like; every value has a safe default inside the mod.");
            sb.AppendLine("return {");
            sb.AppendLine($"    ScanIntervalSeconds = {a.ScanIntervalSeconds},");
            sb.AppendLine($"    TickBudgetMs = {Math.Max(1, a.TickBudgetMs)},");
            sb.AppendLine($"    TickStepMs = {Math.Max(5, a.TickStepMs)},");
            sb.AppendLine($"    ViewRefreshTicks = {Math.Max(1, a.ViewRefreshTicks)},");
            sb.AppendLine($"    FullRefreshTicks = {Math.Max(1, a.FullRefreshTicks)},");
            sb.AppendLine($"    RequireManagerStation = {B(a.RequireManagerStation)},");
            sb.AppendLine($"    DefaultTriggerPercent = {a.DefaultTriggerPercent},");
            sb.AppendLine($"    DefaultKeep = {a.DefaultKeep},");
            sb.AppendLine($"    MaxOrderBatch = {a.MaxOrderBatch},");
            sb.AppendLine($"    IdleGraceSeconds = {a.IdleGraceSeconds},");
            sb.AppendLine($"    MaterialCheck = {B(a.MaterialCheck)},");
            sb.AppendLine($"    AutoChainMaterials = {B(a.AutoChainMaterials)},");
            sb.AppendLine($"    FollowPriorityOrder = {B(a.FollowPriorityOrder)},");
            sb.AppendLine($"    AnnounceLevel = {a.AnnounceLevel},");
            sb.AppendLine($"    IssueRepeatSeconds = {a.IssueRepeatSeconds},");
            sb.AppendLine($"    RemoveOrderCount = {a.RemoveOrderCount},");
            sb.AppendLine($"    Diagnostics = {B(a.Diagnostics)},");
            sb.AppendLine($"    StatusKey = {Q(a.StatusKey ?? "")},");
            sb.AppendLine($"    ClientMenu = {B(a.ClientMenu)},");
            sb.AppendLine($"    MenuKey = {Q(string.IsNullOrEmpty(a.MenuKey) ? "F7" : a.MenuKey)},");
            sb.AppendLine($"    MenuFallbackKey = {Q(string.IsNullOrEmpty(a.MenuFallbackKey) ? "F8" : a.MenuFallbackKey)},");
            sb.AppendLine($"    MenuWidth = {Math.Max(600, a.MenuWidth)},");
            sb.AppendLine($"    MenuHeight = {Math.Max(400, a.MenuHeight)},");
            sb.AppendLine($"    MenuPollMs = {Math.Max(50, a.MenuPollMs)},");
            sb.AppendLine($"    MenuSearchRows = {Math.Max(3, a.MenuSearchRows)},");
            sb.AppendLine($"    WriteStatusToSign = {B(a.WriteStatusToSign)},");
            sb.AppendLine($"    AssignBestWorker = {B(a.AssignBestWorker)},");
            sb.AppendLine($"    ReleaseWorkerWhenDone = {B(a.ReleaseWorkerWhenDone)},");
            sb.AppendLine($"    WorkersPerOrder = {Math.Max(1, a.WorkersPerOrder)},");
            sb.AppendLine($"    InterruptHoldSeconds = {Math.Max(0, a.InterruptHoldSeconds)},");
            sb.AppendLine($"    InterruptMinRemaining = {Math.Max(1, a.InterruptMinRemaining)},");
            sb.AppendLine($"    OpenMenuOnInteract = {B(a.OpenMenuOnInteract)},");
            sb.AppendLine($"    CloseVanillaMenuOnInteract = {B(a.CloseVanillaMenuOnInteract)},");
            sb.AppendLine($"    InteractCloseDelayMs = {Math.Max(0, a.InteractCloseDelayMs)},");
            sb.AppendLine($"    BoardOpenDelayMs = {Math.Max(0, a.BoardOpenDelayMs)},");
            sb.AppendLine("    Stations = {");
            // a Generator copy is a look, not a role, unless it acts as the manager
            foreach (var s in p.Stations.Where(st => st.Enabled && (st.Kind != StationKind.Copy || st.ActsAsManager)))
            {
                // `model` is the concrete model class of the blueprint the row names:
                // the Lua side enumerates that class to find the station in a base.
                // A swapped manager keeps the stand's blueprint, so its class is the
                // stand's, not the chosen model's.
                var model = data?.Building(s.BlueprintSource(data))?.Model ?? data?.Building(s.ReuseMapObjectId)?.Model ?? "";
                var itemsList = s.AllowedItems != null && s.AllowedItems.Count > 0
                    ? ", items = { " + string.Join(", ", s.AllowedItems.Select(Q)) + " }"
                    : "";
                var kind = s.IsManagerRole ? "manager" : KindName(s.Kind);
                sb.AppendLine($"        {Key(s.Id)} = {{ kind = {Q(kind)}, line = {Q(s.Line ?? "")}, name = {Q(s.Name)}, reuse = {Q(s.ReuseMapObjectId)}, model = {Q(model)}{itemsList} }},");
            }
            sb.AppendLine("    },");
            // Model swaps: the manager keeps the stand's blueprint (and functions); the
            // chosen model's mesh and placement box are applied when its actor appears.
            sb.AppendLine("    ModelSwap = {");
            // Also size overrides: mesh scale and the two boxes, applied per placed
            // copy at run time (mesh = "" means keep the blueprint's own mesh).
            foreach (var s in p.Stations.Where(st => st.Enabled && data != null && st.NeedsRuntimeSwap(data)))
            {
                var model = data.Building(s.ReuseMapObjectId);
                var host = data.Building(s.BlueprintSource(data));
                if (model == null || host == null) continue;
                var swapMesh = s.IsModelSwap(data);
                if (swapMesh && string.IsNullOrEmpty(model.MeshPath)) continue;
                var bx = s.OverrideSize ? s.OverlapX : (model.Overlap?.X ?? 0);
                var by = s.OverrideSize ? s.OverlapY : (model.Overlap?.Y ?? 0);
                var bz = s.OverrideSize ? s.OverlapZ : (model.Overlap?.Z ?? 0);
                var wx = s.OverrideSize ? s.WorkX : (model.Workable?.X ?? 0);
                var wy = s.OverrideSize ? s.WorkY : (model.Workable?.Y ?? 0);
                var wz = s.OverrideSize ? s.WorkZ : (model.Workable?.Z ?? 0);
                var vx = s.OverrideSize ? s.BodyX : (model.VirtualMesh?.X ?? 0);
                var vy = s.OverrideSize ? s.BodyY : (model.VirtualMesh?.Y ?? 0);
                var vz = s.OverrideSize ? s.BodyZ : (model.VirtualMesh?.Z ?? 0);
                var scale = s.OverrideSize && s.MeshScale > 0 ? s.MeshScale : 1f;
                var work = wx > 0 && wy > 0 && wz > 0 ? $", work = {{ x = {F(wx)}, y = {F(wy)}, z = {F(wz)} }}" : "";
                var bodyBox = vx > 0 && vy > 0 && vz > 0 ? $", body = {{ x = {F(vx)}, y = {F(vy)}, z = {F(vz)} }}" : "";
                // Box centres relative to the actor: a box is a place as well as a size.
                // The model's own centres, scaled with the extents when a size override
                // changed them, so the box bottom stays where the model's bottom is (the
                // stand's centres sit high and would leave a smaller model's boxes floating).
                static float Tidy(float v) => Math.Abs(v) < 0.01f ? 0f : v;
                string At(string key, BoxHalf b, float ex, float ey, float ez)
                {
                    if (b?.At == null) return "";
                    var rx = b.X > 0 ? ex / b.X : 1f;
                    var ry = b.Y > 0 ? ey / b.Y : 1f;
                    var rz = b.Z > 0 ? ez / b.Z : 1f;
                    return $", {key} = {{ x = {F(Tidy(b.At.X * rx))}, y = {F(Tidy(b.At.Y * ry))}, z = {F(Tidy(b.At.Z * rz))} }}";
                }
                var boxAt = At("box_at", model.Overlap, bx, by, bz);
                var workAt = work.Length > 0 ? At("work_at", model.Workable, wx, wy, wz) : "";
                var bodyAt = bodyBox.Length > 0 ? At("body_at", model.VirtualMesh, vx, vy, vz) : "";
                // the prompt volume (F / V / C) follows the model too, scaled like the placement box
                var interact = "";
                var ib = model.Interact;
                if (ib != null && ib.X > 0 && ib.Y > 0 && ib.Z > 0)
                {
                    var sx = model.Overlap != null && model.Overlap.X > 0 ? bx / model.Overlap.X : 1f;
                    var sy = model.Overlap != null && model.Overlap.Y > 0 ? by / model.Overlap.Y : 1f;
                    var sz = model.Overlap != null && model.Overlap.Z > 0 ? bz / model.Overlap.Z : 1f;
                    var ix = ib.X * sx; var iy = ib.Y * sy; var iz = ib.Z * sz;
                    interact = $", interact = {{ x = {F(ix)}, y = {F(iy)}, z = {F(iz)} }}" + At("interact_at", ib, ix, iy, iz);
                }
                sb.AppendLine($"        {Key(s.Id)} = {{ class = {Q(host.BlueprintSoft)}, mesh = {Q(swapMesh ? model.MeshPath : "")}, model = {Q(model.MapObjectId)}, scale = {F(scale)}, box = {{ x = {F(bx)}, y = {F(by)}, z = {F(bz)} }}{boxAt}{work}{workAt}{bodyBox}{bodyAt}{interact} }},");
            }
            sb.AppendLine("    },");
            // Item links for vanilla production lines: "this line may only make these".
            sb.AppendLine("    Facilities = {");
            foreach (var kv in p.FacilityLinks.Where(k => k.Value != null && k.Value.Count > 0).OrderBy(k => k.Key, StringComparer.Ordinal))
                sb.AppendLine($"        {Key(kv.Key)} = {{ items = {{ {string.Join(", ", kv.Value.Select(Q))} }} }},");
            sb.AppendLine("    },");
            sb.AppendLine("    Presets = {");
            foreach (var t in p.Presets)
            {
                var trigger = t.Trigger > 0 ? t.Trigger.ToString(CultureInfo.InvariantCulture) : "nil";
                sb.AppendLine($"        {{ item = {Q(t.ItemId)}, keep = {t.Keep}, trigger = {trigger}, priority = {t.Priority}, line = {Q(string.IsNullOrEmpty(t.Line) ? "default" : t.Line)}, top = {B(t.Top)}, weight = {Math.Max(1, t.Weight)}{(string.IsNullOrEmpty(t.Only) ? "" : $", only = {Q(t.Only)}")} }},");
            }
            sb.AppendLine("    },");
            // The chain station: what F opens, what the chain screen may do, which
            // producer families and bench types automation tracks, how targets are served.
            var c = p.Chain ?? new ChainSettings();
            sb.AppendLine("    Chain = {");
            sb.AppendLine($"        InteractTab = {Q(string.IsNullOrEmpty(c.InteractTab) ? "chain" : c.InteractTab)},");
            sb.AppendLine($"        DefaultTab = {Q(string.IsNullOrEmpty(c.DefaultTab) ? "chain" : c.DefaultTab)},");
            sb.AppendLine($"        CTab = {Q(string.IsNullOrEmpty(c.CTab) ? "targets" : c.CTab)},");
            sb.AppendLine($"        KeepAssignBoard = {B(c.CTab == "vanilla")},");
            sb.AppendLine($"        AllowCancelFromList = {B(c.AllowCancelFromList)},");
            sb.AppendLine($"        ShowMakeNow = {B(c.ShowMakeNow)},");
            sb.AppendLine($"        ProductSlotOpensBench = {B(c.ProductSlotOpensBench)},");
            sb.AppendLine($"        ProductSlotIndicator = {Math.Max(0, c.ProductSlotIndicator)},");
            sb.AppendLine($"        BoardHeaders = {B(c.BoardHeaders)},");
            sb.AppendLine($"        BoardShowUntracked = {B(c.BoardShowUntracked)},");
            sb.AppendLine($"        BoardHudFallback = {B(c.BoardHudFallback)},");
            sb.AppendLine($"        PromptText = {B(c.PromptText)},");
            sb.AppendLine($"        PromptF = {Q(string.IsNullOrEmpty(c.PromptF) ? "Fixed work assignments" : c.PromptF)},");
            sb.AppendLine($"        PromptC = {Q(string.IsNullOrEmpty(c.PromptC) ? "Production targets" : c.PromptC)},");
            sb.AppendLine($"        PromptRangeCm = {Math.Max(50, c.PromptRangeCm)},");
            sb.AppendLine($"        OneProducerPerTarget = {B(c.OneProducerPerTarget)},");
            sb.AppendLine($"        RankBy = {Q(string.IsNullOrEmpty(c.RankBy) ? "rank" : c.RankBy)},");
            sb.AppendLine($"        TargetOrder = {Q(string.IsNullOrEmpty(c.TargetOrder) ? "lottery" : c.TargetOrder)},");
            sb.AppendLine("        Families = {");
            foreach (var f in ChainCatalog.Families)
                sb.AppendLine($"            {{ id = {Q(f.Id)}, label = {Q(f.Label)}, enabled = {B(c.FamilyEnabled(f.Id))} }},");
            sb.AppendLine("        },");
            var excluded = (c.ExcludedBenches ?? new List<string>()).Where(s => !string.IsNullOrEmpty(s)).Distinct().OrderBy(s => s, StringComparer.Ordinal).Select(Q).ToList();
            sb.AppendLine(excluded.Count == 0 ? "        ExcludedBenches = { }," : $"        ExcludedBenches = {{ {string.Join(", ", excluded)} }},");
            sb.AppendLine("    },");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string Items(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_items.lua : every item id with its English name, type and rank.");
            sb.AppendLine("-- GENERATED from DT_ItemDataTable + DT_ItemNameText_Common by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var i in data.Items.OrderBy(i => i.Id, StringComparer.Ordinal))
            {
                sb.Append("  ").Append(Key(i.Id)).Append(" = { name = ").Append(Q(i.Name ?? ""))
                  .Append(", typeA = ").Append(Q(i.TypeA ?? "None"))
                  .Append(", typeB = ").Append(Q(i.TypeB ?? "None"))
                  .Append(", rank = ").Append(i.Rank.ToString(CultureInfo.InvariantCulture))
                  .Append(", sort = ").Append(i.SortId.ToString(CultureInfo.InvariantCulture))
                  .AppendLine(" },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string Recipes(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_recipes.lua : every crafting recipe (row key, product, per-craft count, work, materials).");
            sb.AppendLine("-- GENERATED from DT_ItemRecipeDataTable by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var kv in data.Recipes.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                var r = kv.Value;
                sb.Append("  ").Append(Key(kv.Key)).Append(" = { product = ").Append(Q(r.Product))
                  .Append(", count = ").Append(Math.Max(1, r.Count).ToString(CultureInfo.InvariantCulture))
                  .Append(", work = ").Append(N(r.Work));
                if (!string.IsNullOrEmpty(r.Tech)) sb.Append(", tech = ").Append(Q(r.Tech));
                sb.Append(", materials = {");
                foreach (var m in r.Materials)
                    sb.Append(" { id = ").Append(Q(m.Id)).Append(", count = ").Append(m.Count.ToString(CultureInfo.InvariantCulture)).Append(" },");
                sb.AppendLine(" } },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string Enums(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_enums.lua : EPalItemTypeA / EPalItemTypeB / EPalWorkSuitability value order (index = byte value + 1).");
            sb.AppendLine("-- GENERATED from the game's property mappings by PalItemgen.");
            sb.AppendLine("return {");
            sb.Append("  itemTypeA = { ").Append(string.Join(", ", data.Enums.ItemTypeA.Select(Q))).AppendLine(" },");
            sb.Append("  itemTypeB = { ").Append(string.Join(", ", data.Enums.ItemTypeB.Select(Q))).AppendLine(" },");
            sb.Append("  workSuitability = { ").Append(string.Join(", ", data.Enums.WorkSuitability.Select(Q))).AppendLine(" },");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Which work type each vanilla bench needs (its first real assignment
        /// row). Ancient benches carry None: any Pal may work them.
        /// </summary>
        public static string Benches(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_benches.lua : work suitability each crafting bench needs (from DT_MapObjectAssignData),");
            sb.AppendLine("-- plus the chain screen's family (TypeUIDisplay), craft rank max, data work speed (0 = basic tier), tech tier, fixed work spots and buildable flag.");
            sb.AppendLine("-- GENERATED by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var p in data.Producers.Where(p => p.MapObjectId != null).OrderBy(p => p.MapObjectId, StringComparer.Ordinal))
            {
                var a = p.Assignments.FirstOrDefault(x => x.WorkSuitability != "Anyone") ?? p.Assignments.FirstOrDefault();
                var suit = a?.WorkSuitability ?? "None";
                sb.Append("  ").Append(Key(p.MapObjectId)).Append(" = { name = ").Append(Q(p.Name ?? p.MapObjectId)).Append(", suitability = ").Append(Q(suit))
                  .Append(", rank = ").Append((a?.WorkSuitabilityRank ?? 1).ToString(CultureInfo.InvariantCulture))
                  .Append(", workerMax = ").Append((a?.WorkerMaxNum ?? 0).ToString(CultureInfo.InvariantCulture))
                  .Append(", family = ").Append(Q(p.Build?.TypeUIDisplay ?? "None"))
                  .Append(", rankMax = ").Append((p.RankMax ?? 0).ToString(CultureInfo.InvariantCulture))
                  .Append(", speed = ").Append(F(p.WorkSpeed ?? 0f))
                  .Append(", tier = ").Append((p.Tech?.LevelCap ?? 0).ToString(CultureInfo.InvariantCulture))
                  .Append(", spots = ").Append(ChainCatalog.WorkSpots(data, p.MapObjectId).ToString(CultureInfo.InvariantCulture))
                  .Append(", buildable = ").Append(B(p.Buildable))
                  .AppendLine(" },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>The Monitoring Stand's work modes and their effects, for the menu's first tab.</summary>
        public static string WorkHard(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_workhard.lua : Monitoring Stand work modes (BP_PalGameSetting.BaseCampPassiveEffectWorkHardInfoMap).");
            sb.AppendLine("-- GENERATED by PalItemgen. Live values are read from PalGameSetting in game when possible.");
            sb.AppendLine("return {");
            foreach (var w in data.WorkHard)
            {
                sb.Append("  { mode = ").Append(Q(w.Mode))
                  .Append(", workSpeed = ").Append(N(w.WorkSpeedRate))
                  .Append(", moveSpeed = ").Append(N(w.MoveSpeedRate))
                  .Append(", sanity = ").Append(N(w.AffectSanityRate))
                  .Append(", hunger = ").Append(N(w.DecreaseFullStomachRate))
                  .AppendLine(" },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Item icon texture paths (DT_ItemIconDataTable) for the menu's search list.</summary>
        public static string Icons(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_icons.lua : item id -> icon texture path (from DT_ItemIconDataTable).");
            sb.AppendLine("-- GENERATED by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var i in data.Items.Where(i => !string.IsNullOrEmpty(i.Icon)).OrderBy(i => i.Id, StringComparer.Ordinal))
                sb.Append("  ").Append(Key(i.Id)).Append(" = ").Append(Q(i.Icon)).AppendLine(",");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Every Pal species' work suitability ranks and base craft speed, the offline fallback for ranking workers.</summary>
        /// <summary>Every buildable building: name, build icon and Pal requirement, for the Assignment Board rows.</summary>
        public static string Buildings(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_buildings.lua : every building's name, icon and Pal requirement (DT_BuildObjectIconDataTable + DT_MapObjectAssignData).");
            sb.AppendLine("-- GENERATED by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var b in data.Buildings.Where(b => !string.IsNullOrEmpty(b.MapObjectId)).OrderBy(b => b.MapObjectId, StringComparer.Ordinal))
            {
                var a = b.Assignments.FirstOrDefault(x => x.WorkSuitability != "Anyone") ?? b.Assignments.FirstOrDefault();
                var suit = a?.WorkSuitability ?? "None";
                var icon = b.Icon ?? (data.Icons.TryGetValue(b.MapObjectId, out var ic) ? ic.Path : "");
                sb.Append("  ").Append(Key(b.MapObjectId)).Append(" = { name = ").Append(Q(string.IsNullOrEmpty(b.Name) ? b.MapObjectId : b.Name))
                  .Append(", icon = ").Append(Q(icon ?? ""))
                  .Append(", suitability = ").Append(Q(suit))
                  .Append(", rank = ").Append((a?.WorkSuitabilityRank ?? 1).ToString(CultureInfo.InvariantCulture))
                  .Append(", workerMax = ").Append((a?.WorkerMaxNum ?? 0).ToString(CultureInfo.InvariantCulture))
                  .AppendLine(" },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string Pals(GameData data)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- pm_data_pals.lua : work suitability ranks per Pal species (from DT_PalMonsterParameter).");
            sb.AppendLine("-- GENERATED by PalItemgen.");
            sb.AppendLine("return {");
            foreach (var p in data.Pals.OrderBy(p => p.Id, StringComparer.Ordinal))
            {
                sb.Append("  ").Append(Key(p.Id)).Append(" = { name = ").Append(Q(p.Name ?? ""))
                  .Append(", craft = ").Append(p.CraftSpeed.ToString(CultureInfo.InvariantCulture))
                  .Append(", ranks = {");
                foreach (var kv in p.Ranks.OrderBy(k => k.Key, StringComparer.Ordinal))
                    sb.Append(' ').Append(Key(kv.Key)).Append(" = ").Append(kv.Value.ToString(CultureInfo.InvariantCulture)).Append(',');
                sb.AppendLine(" } },");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
