// <auto-generated>
//     Generated by Tools/PalCreationEngine/generate_model.py from
//     Assets/StreamingAssets/PalCreationEngine/pal_schema.json
//
//     Do not edit by hand. Re-run the generator after a Palworld update:
//         python Tools/PalCreationEngine/generate_lookups.py
//         python Tools/PalCreationEngine/generate_model.py
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

namespace PalCreationEngine.Data
{

    /// <summary>
    /// A bare XYZ triple, matching how the data tables serialize
    /// MeshRelativeLocation. Not UnityEngine.Vector3: that serializes with
    /// extra members and float noise, which would corrupt the emitted row.
    /// </summary>
    public sealed class PalVector
    {
        [JsonProperty("X", Order = 0)] public float X;
        [JsonProperty("Y", Order = 1)] public float Y;
        [JsonProperty("Z", Order = 2)] public float Z;

        public PalVector() { }

        public PalVector(float x, float y, float z)
        {
            X = x;
            Y = y;
            Z = z;
        }
    }

    /// <summary>
    /// One DT_PalMonsterParameter row: the 90 fields that define a Pal, plus
    /// one optional base-table field (IsUncapturable).
    /// 
    /// Field order here reproduces the real table exactly. All 753 shipped
    /// rows share one identical key order, and Order = n pins it so
    /// serialization cannot drift from it. The verified working new-Pal mod
    /// (PalVariantPandemonium, Workshop 3800182837) writes exactly the first
    /// 90 of those fields in this order in every one of its 100 pals/ rows and
    /// omits IsUncapturable; a row with IsUncapturable left null therefore
    /// serializes to the working mod's exact shape.
    /// 
    /// Every field is nullable and nulls are omitted on write, so the same
    /// type serves both PalSchema modes: leave a field null to keep an
    /// existing Pal's real value, or populate all 90 for a new Pal (which
    /// has no base row to inherit from).
    /// </summary>
    public sealed class PalMonsterParameterRow
    {
        [JsonProperty("OverrideNameTextID", Order = 0)] public string OverrideNameTextID;

        [JsonProperty("NamePrefixID", Order = 1)] public string NamePrefixID;

        /// <summary>Real values: None, PARTNERSKILL_DUMMY_None</summary>
        [JsonProperty("OverridePartnerSkillNameTextID", Order = 2)] public string OverridePartnerSkillNameTextID;

        /// <summary>Real values: None, PAL_FIRST_SPAWN_DESC_Human</summary>
        [JsonProperty("OverridePartnerSkillDescTextID", Order = 3)] public string OverridePartnerSkillDescTextID;

        [JsonProperty("IsPal", Order = 4)] public bool? IsPal;

        [JsonProperty("Tribe", Order = 5)] public string Tribe;

        [JsonProperty("BPClass", Order = 6)] public string BPClass;

        /// <summary>Real observed range: -2 to 204.</summary>
        [JsonProperty("ZukanIndex", Order = 7)] public int? ZukanIndex;

        /// <summary>Real values: , B</summary>
        [JsonProperty("ZukanIndexSuffix", Order = 8)] public string ZukanIndexSuffix;

        /// <summary>Real values: EPalSizeType::L, EPalSizeType::M, EPalSizeType::S, EPalSizeType::XL, EPalSizeType::XS</summary>
        [JsonProperty("Size", Order = 9)] public string Size;

        /// <summary>Real observed range: 0 to 20.</summary>
        [JsonProperty("Rarity", Order = 10)] public int? Rarity;

        /// <summary>Real values: EPalElementType::Dark, EPalElementType::Dragon, EPalElementType::Earth, EPalElementType::Electricity, EPalElementType::Fire, EPalElementType::Ice, EPalElementType::Leaf, EPalElementType::None, ... (10 total)</summary>
        [JsonProperty("ElementType1", Order = 11)] public string ElementType1;

        /// <summary>Real values: EPalElementType::Dark, EPalElementType::Dragon, EPalElementType::Earth, EPalElementType::Electricity, EPalElementType::Fire, EPalElementType::Ice, EPalElementType::Leaf, EPalElementType::None, ... (10 total)</summary>
        [JsonProperty("ElementType2", Order = 12)] public string ElementType2;

        /// <summary>Real values: EPalGenusCategoryType::Bird, EPalGenusCategoryType::Dragon, EPalGenusCategoryType::Fish, EPalGenusCategoryType::FourLegged, EPalGenusCategoryType::Humanoid, EPalGenusCategoryType::Monster, EPalGenusCategoryType::None, EPalGenusCategoryType::Other</summary>
        [JsonProperty("GenusCategory", Order = 13)] public string GenusCategory;

        /// <summary>Real values: EPalOrganizationType::Ally, EPalOrganizationType::None</summary>
        [JsonProperty("Organization", Order = 14)] public string Organization;

        /// <summary>Real values: EPalWeaponType::None</summary>
        [JsonProperty("Weapon", Order = 15)] public string Weapon;

        [JsonProperty("WeaponEquip", Order = 16)] public bool? WeaponEquip;

        /// <summary>Real observed range: 60 to 288.</summary>
        [JsonProperty("Hp", Order = 17)] public int? Hp;

        /// <summary>Real observed range: 50 to 150.</summary>
        [JsonProperty("MeleeAttack", Order = 18)] public int? MeleeAttack;

        /// <summary>Real observed range: 50 to 200.</summary>
        [JsonProperty("ShotAttack", Order = 19)] public int? ShotAttack;

        /// <summary>Real observed range: 50 to 200.</summary>
        [JsonProperty("Defense", Order = 20)] public int? Defense;

        /// <summary>Real observed range: 30 to 150.</summary>
        [JsonProperty("Support", Order = 21)] public int? Support;

        /// <summary>Constant 100 across all real Pals.</summary>
        [JsonProperty("CraftSpeed", Order = 22)] public int? CraftSpeed;

        /// <summary>Real observed range: 0.1 to 6.0.</summary>
        [JsonProperty("Friendship_HP", Order = 23)] public float? Friendship_HP;

        /// <summary>Real observed range: 1.0 to 4.5.</summary>
        [JsonProperty("Friendship_ShotAttack", Order = 24)] public float? Friendship_ShotAttack;

        /// <summary>Real observed range: 1.0 to 4.5.</summary>
        [JsonProperty("Friendship_Defense", Order = 25)] public float? Friendship_Defense;

        /// <summary>Constant 0.0 across all real Pals.</summary>
        [JsonProperty("Friendship_CraftSpeed", Order = 26)] public float? Friendship_CraftSpeed;

        /// <summary>Real observed range: 1.0 to 500.0.</summary>
        [JsonProperty("EnemyMaxHPRate", Order = 27)] public float? EnemyMaxHPRate;

        /// <summary>Real observed range: 0.04 to 2.0.</summary>
        [JsonProperty("EnemyReceiveDamageRate", Order = 28)] public float? EnemyReceiveDamageRate;

        /// <summary>Real observed range: 0.7 to 13.0.</summary>
        [JsonProperty("EnemyInflictDamageRate", Order = 29)] public float? EnemyInflictDamageRate;

        /// <summary>Real observed range: 1.0 to 3.0.</summary>
        [JsonProperty("EnemyWazaCoolTimeRate", Order = 30)] public float? EnemyWazaCoolTimeRate;

        /// <summary>Real observed range: 0.49 to 1.5.</summary>
        [JsonProperty("CaptureRateCorrect", Order = 31)] public float? CaptureRateCorrect;

        /// <summary>Real observed range: 1.0 to 40.0.</summary>
        [JsonProperty("ExpRatio", Order = 32)] public float? ExpRatio;

        /// <summary>Real observed range: 313.0 to 40000.0.</summary>
        [JsonProperty("Price", Order = 33)] public float? Price;

        /// <summary>Real observed range: 1.0 to 100.0.</summary>
        [JsonProperty("StatusResistUpRate", Order = 34)] public float? StatusResistUpRate;

        /// <summary>Real values: Boss, Escape, Escape_to_Battle, Friendly, Kill_All, NotInterested, Warlike, Warlike_Anyway, ... (9 total)</summary>
        [JsonProperty("AIResponse", Order = 35)] public string AIResponse;

        /// <summary>Real values: None</summary>
        [JsonProperty("AISightResponse", Order = 36)] public string AISightResponse;

        /// <summary>Real observed range: -1 to 3000.</summary>
        [JsonProperty("SlowWalkSpeed", Order = 37)] public int? SlowWalkSpeed;

        /// <summary>Real observed range: -1 to 3000.</summary>
        [JsonProperty("WalkSpeed", Order = 38)] public int? WalkSpeed;

        /// <summary>Real observed range: -1 to 5000.</summary>
        [JsonProperty("RunSpeed", Order = 39)] public int? RunSpeed;

        /// <summary>Real observed range: -1 to 7600.</summary>
        [JsonProperty("RideSprintSpeed", Order = 40)] public int? RideSprintSpeed;

        /// <summary>Real observed range: -1 to 3000.</summary>
        [JsonProperty("TransportSpeed", Order = 41)] public int? TransportSpeed;

        /// <summary>Real observed range: -1 to 3000.</summary>
        [JsonProperty("SwimSpeed", Order = 42)] public int? SwimSpeed;

        /// <summary>Real observed range: -1 to 3000.</summary>
        [JsonProperty("SwimDashSpeed", Order = 43)] public int? SwimDashSpeed;

        [JsonProperty("IsBoss", Order = 44)] public bool? IsBoss;

        [JsonProperty("IsTowerBoss", Order = 45)] public bool? IsTowerBoss;

        [JsonProperty("IsRaidBoss", Order = 46)] public bool? IsRaidBoss;

        [JsonProperty("UseBossHPGauge", Order = 47)] public bool? UseBossHPGauge;

        /// <summary>Real values: EPalBattleBGMType::Cool, EPalBattleBGMType::Cute, EPalBattleBGMType::EyeofCthulhu, EPalBattleBGMType::FieldBoss_Tier_1, EPalBattleBGMType::FieldBoss_Tier_2, EPalBattleBGMType::FieldBoss_Tier_3, EPalBattleBGMType::FieldBoss_Tier_4, EPalBattleBGMType::FieldBoss_Tier_5, ... (20 total)</summary>
        [JsonProperty("BattleBGM", Order = 48)] public string BattleBGM;

        [JsonProperty("IgnoreLeanBack", Order = 49)] public bool? IgnoreLeanBack;

        [JsonProperty("IgnoreBlowAway", Order = 50)] public bool? IgnoreBlowAway;

        [JsonProperty("IgnoreStun", Order = 51)] public bool? IgnoreStun;

        /// <summary>Real observed range: 100 to 730.</summary>
        [JsonProperty("MaxFullStomach", Order = 52)] public int? MaxFullStomach;

        /// <summary>Constant 1.0 across all real Pals.</summary>
        [JsonProperty("FullStomachDecreaseRate", Order = 53)] public float? FullStomachDecreaseRate;

        /// <summary>Real observed range: 1 to 9.</summary>
        [JsonProperty("FoodAmount", Order = 54)] public int? FoodAmount;

        /// <summary>Constant 25 across all real Pals.</summary>
        [JsonProperty("ViewingDistance", Order = 55)] public int? ViewingDistance;

        /// <summary>Real observed range: 90 to 360.</summary>
        [JsonProperty("ViewingAngle", Order = 56)] public int? ViewingAngle;

        /// <summary>Constant 1.0 across all real Pals.</summary>
        [JsonProperty("HearingRate", Order = 57)] public float? HearingRate;

        [JsonProperty("NooseTrap", Order = 58)] public bool? NooseTrap;

        [JsonProperty("Nocturnal", Order = 59)] public bool? Nocturnal;

        /// <summary>Real observed range: 0 to 999.</summary>
        [JsonProperty("BiologicalGrade", Order = 60)] public int? BiologicalGrade;

        [JsonProperty("Predator", Order = 61)] public bool? Predator;

        [JsonProperty("Edible", Order = 62)] public bool? Edible;

        /// <summary>Real observed range: 70 to 410.</summary>
        [JsonProperty("Stamina", Order = 63)] public int? Stamina;

        /// <summary>Real observed range: -1 to 100.</summary>
        [JsonProperty("MaleProbability", Order = 64)] public int? MaleProbability;

        /// <summary>Real observed range: 10 to 9999.</summary>
        [JsonProperty("CombiRank", Order = 65)] public int? CombiRank;

        /// <summary>Real observed range: 571 to 999900.</summary>
        [JsonProperty("CombiDuplicatePriority", Order = 66)] public int? CombiDuplicatePriority;

        [JsonProperty("IgnoreCombi", Order = 67)] public bool? IgnoreCombi;

        /// <summary>Real observed range: 0.0 to 600.0.</summary>
        [JsonProperty("MeshCapsuleHalfHeight", Order = 68)] public float? MeshCapsuleHalfHeight;

        /// <summary>Real observed range: -30.0 to 500.0.</summary>
        [JsonProperty("MeshCapsuleRadius", Order = 69)] public float? MeshCapsuleRadius;

        [JsonProperty("MeshRelativeLocation", Order = 70)] public PalVector MeshRelativeLocation;

        /// <summary>Real values: EPalWorkSuitability::Collection, EPalWorkSuitability::Cool, EPalWorkSuitability::Deforest, EPalWorkSuitability::EmitFlame, EPalWorkSuitability::GenerateElectricity, EPalWorkSuitability::Handcraft, EPalWorkSuitability::Mining, EPalWorkSuitability::MonsterFarm, ... (12 total)</summary>
        [JsonProperty("BestWorkSuitability", Order = 71)] public string BestWorkSuitability;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_EmitFlame", Order = 72)] public int? WorkSuitability_EmitFlame;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Watering", Order = 73)] public int? WorkSuitability_Watering;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Seeding", Order = 74)] public int? WorkSuitability_Seeding;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_GenerateElectricity", Order = 75)] public int? WorkSuitability_GenerateElectricity;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Handcraft", Order = 76)] public int? WorkSuitability_Handcraft;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Collection", Order = 77)] public int? WorkSuitability_Collection;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Deforest", Order = 78)] public int? WorkSuitability_Deforest;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Mining", Order = 79)] public int? WorkSuitability_Mining;

        /// <summary>Constant 0 across all real Pals.</summary>
        [JsonProperty("WorkSuitability_OilExtraction", Order = 80)] public int? WorkSuitability_OilExtraction;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_ProductMedicine", Order = 81)] public int? WorkSuitability_ProductMedicine;

        /// <summary>Real observed range: 0 to 8.</summary>
        [JsonProperty("WorkSuitability_Cool", Order = 82)] public int? WorkSuitability_Cool;

        /// <summary>Real observed range: 0 to 7.</summary>
        [JsonProperty("WorkSuitability_Transport", Order = 83)] public int? WorkSuitability_Transport;

        /// <summary>Real observed range: 0 to 4.</summary>
        [JsonProperty("WorkSuitability_MonsterFarm", Order = 84)] public int? WorkSuitability_MonsterFarm;

        /// <summary>Real values: Alien, Deffence_up1, Deffence_up2_2, ElementBoost_Aqua_2_PAL, ElementBoost_Earth_2_PAL, ElementBoost_Fire_2_PAL, ElementBoost_Leaf_2_PAL, ElementBoost_Thunder_2_PAL, ... (20 total)</summary>
        [JsonProperty("PassiveSkill1", Order = 85)] public string PassiveSkill1;

        /// <summary>Real values: Alien, ElementBoost_Dark_2_PAL, ElementBoost_Dragon_2_PAL, ElementBoost_Ice_2_PAL, ElementBoost_Normal_2_PAL, None, Nushi</summary>
        [JsonProperty("PassiveSkill2", Order = 86)] public string PassiveSkill2;

        /// <summary>Real values: None</summary>
        [JsonProperty("PassiveSkill3", Order = 87)] public string PassiveSkill3;

        /// <summary>Real values: None</summary>
        [JsonProperty("PassiveSkill4", Order = 88)] public string PassiveSkill4;

        [JsonProperty("FirstDefeatRewardItemID", Order = 89)] public string FirstDefeatRewardItemID;

        /// <summary>
        /// Last field of the real table (index 90). The verified working mod omits
        /// it from every row, so it is OPTIONAL: leave null to emit the working
        /// mod's 90-field shape; set it only to mark a Pal uncapturable.
        /// Real values: true, false.
        /// </summary>
        [JsonProperty("IsUncapturable", Order = 90)] public bool? IsUncapturable;

        /// <summary>
        /// Base-table fields the verified working mod never writes. Completeness
        /// checks and the factory skip these, so a new Pal matches the working
        /// mod's row shape unless the author sets one on purpose.
        /// </summary>
        public static readonly HashSet<string> OptionalFields =
            new HashSet<string> { nameof(IsUncapturable) };
    }

    /// <summary>
    /// One DT_PalDropItem_Common row: a Pal's 10 loot slots.
    /// 
    /// Row key convention is "{CharacterID}{Level:000}" -- Alpaca at level
    /// tier 0 is row "Alpaca000".
    /// </summary>
    public sealed class PalDropItemRow
    {
        [JsonProperty("CharacterID", Order = 0)] public string CharacterID;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Level", Order = 1)] public int? Level;

        [JsonProperty("ItemId1", Order = 2)] public string ItemId1;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate1", Order = 3)] public float? Rate1;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min1", Order = 4)] public int? min1;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max1", Order = 5)] public int? Max1;

        [JsonProperty("ItemId2", Order = 6)] public string ItemId2;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate2", Order = 7)] public float? Rate2;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min2", Order = 8)] public int? min2;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max2", Order = 9)] public int? Max2;

        [JsonProperty("ItemId3", Order = 10)] public string ItemId3;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate3", Order = 11)] public float? Rate3;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min3", Order = 12)] public int? min3;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max3", Order = 13)] public int? Max3;

        [JsonProperty("ItemId4", Order = 14)] public string ItemId4;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate4", Order = 15)] public float? Rate4;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min4", Order = 16)] public int? min4;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max4", Order = 17)] public int? Max4;

        [JsonProperty("ItemId5", Order = 18)] public string ItemId5;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate5", Order = 19)] public float? Rate5;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min5", Order = 20)] public int? min5;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max5", Order = 21)] public int? Max5;

        [JsonProperty("ItemId6", Order = 22)] public string ItemId6;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate6", Order = 23)] public float? Rate6;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min6", Order = 24)] public int? min6;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max6", Order = 25)] public int? Max6;

        [JsonProperty("ItemId7", Order = 26)] public string ItemId7;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate7", Order = 27)] public float? Rate7;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min7", Order = 28)] public int? min7;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max7", Order = 29)] public int? Max7;

        [JsonProperty("ItemId8", Order = 30)] public string ItemId8;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate8", Order = 31)] public float? Rate8;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min8", Order = 32)] public int? min8;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max8", Order = 33)] public int? Max8;

        [JsonProperty("ItemId9", Order = 34)] public string ItemId9;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate9", Order = 35)] public float? Rate9;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min9", Order = 36)] public int? min9;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max9", Order = 37)] public int? Max9;

        [JsonProperty("ItemId10", Order = 38)] public string ItemId10;

        /// <summary>Real observed range: 0.0 to 100.0.</summary>
        [JsonProperty("Rate10", Order = 39)] public float? Rate10;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("min10", Order = 40)] public int? min10;

        /// <summary>Real observed range: 0 to 0.</summary>
        [JsonProperty("Max10", Order = 41)] public int? Max10;
    }
}
